library(testthat)
source("../R/bagging.R")

context("bagging ensemble classifier")
test_that("prediction returns the class receiving the most votes in a sample with ties broken at random",{
  sample<-c("standing","standing","standing")
  expect_equal(prediction(sample),"standing")
  sample<-c("standing","standing","sitting")
  expect_equal(prediction(sample),"standing")
  sample<-c("standing","sitting","sitting")
  expect_equal(prediction(sample),"sitting")
  sample<-c("standing","sitting","sitting","standing")
  expect_true(prediction(sample) %in% c("sitting","standing"))
  sample<-c("standing","sitting","sitting","sitting")
  expect_equal(prediction(sample),"sitting")
  sample<-c("standing","sitting","sitting","sitting","laying","walking downstairs")
  expect_equal(prediction(sample),"sitting")
  sample<-c("a","a","a","b","b")
  expect_equal(prediction(sample),"a")
})

test_that("maxVoteCount returns the max vote count for a class (or classes in case of tie)",{
  sample<-c("standing","sitting","sitting","sitting","laying","walking downstairs")
  expect_equal(maxVoteCount(sample),3)
  sample<-c("standing","standing","standing","sitting","sitting","sitting","laying","walking downstairs")
  expect_equal(maxVoteCount(sample),3)
  sample<-c("sitting","standing","standing","standing","sitting","sitting","sitting","laying","walking downstairs")
  expect_equal(maxVoteCount(sample),4)
  sample<-c("sitting","standing","laying","walking downstairs")
  expect_equal(maxVoteCount(sample),1)
})

test_that("maxClasses returns the names of the class or classes receiving the most votes in sample",{
  sample<-c("standing","sitting","sitting","sitting","laying","walking downstairs")
  expect_equal(maxClasses(sample),"sitting")
  sample<-c("standing","standing","standing","sitting","sitting","sitting","laying","walking downstairs")
  expect_equal(setdiff(maxClasses(sample),c("sitting","standing")),character(0)) 
  sample<-c("sitting","standing","standing","standing","sitting","sitting","sitting","laying","walking downstairs")
  expect_equal(maxClasses(sample),"sitting")
  sample<-c("sitting","standing","laying","walking downstairs")
  expect_equal(setdiff(maxClasses(sample),c("sitting","standing","laying","walking downstairs")),character(0))
})